// "use client";
import type { Metadata } from "next";
import "./globals.css";

// import { Montserrat } from "next/font/google";

import Navbar from "@/components/Navbar";
import React from "react";

// const montserrat = Montserrat({
//   subsets: ["latin"],
//   variable: "--font-montserrat",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { useSelectedLayoutSegment } from "next/navigation";

export default function RootLayout({
  children,
  contact,
  about,
  customtours,
}: Readonly<{
  children: React.ReactNode;
  contact: React.ReactNode;
  about: React.ReactNode;
  customtours: React.ReactNode;
}>) {
  // const segment = useSelectedLayoutSegment();

  return (
    <html lang="en">
      <body className={`scroll-smooth	debug-screens bg-background`}>
        <Navbar />
        <main className="xl:mt-[-120px] bg-background">{children}</main>
      </body>
    </html>
  );
}
